import { AppBootstrap } from '@/AppBootstrap';
import Navbar from '@/Presentation/Components/Navigation/Navbar/Navbar';
import type { Metadata } from 'next';
import '../Presentation/Styles/fonts.css';
import '../Presentation/Styles/index.css';

export const metadata: Metadata = {
   title: 'Victor Deleau | Portfolio',
   description: 'Generated by create next app'
};

export default async function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   await AppBootstrap.initialize();
   return (
      <html lang="en">
         <body>
            <Navbar />
            {children}
         </body>
      </html>
   );
}
